### PR TITLE
Fix sitemap

### LINKED ISSUE #328: Sitemap.xml has source paths instead of page URLs
We noticed on the Salt site, that the `sitemap.xml` files generated by Mosaic are incorrect (jpmorganchase/salt-ds#1559):

### Description

The `sitemap.xml` files generated by Mosaic are incorrect. The contents of `<loc>` needs to be the full URL to the page (see https://www.sitemaps.org/protocol.html), but instead seems to have the path to the source MDX file.

### Steps to reproduce

Check the `sitemap.xml` file being generated by Mosaic. For example, visit https://www.saltdesignsystem.com/sitemap.xml

### Expected behavior

The contents of `sitemap.xml` should conform to the specification.

### PR DESCRIPTION
**Pull request by lilyvc**
This PR (closes #328):
1. Adds the option 'siteUrl' to the Sitemap plugin. This option is used to generate sitemaps with complete urls.
2. Uses this option in fs.config, passing in process.env.SITE_URL.
3. Adds SITE_URL to our env file.
4. Regens our sitemap files.

### CODE REVIEW

File: packages/plugins/src/SiteMapPlugin.ts [hunk 1]
```diff
@@ -1,12 +1,13 @@
...
+import path from 'path';
 
 interface SiteMapPluginConfigData {
   sitemaps: Array<string[]>;
 }
 
 const SiteMapPlugin: PluginType<Page, unknown, SiteMapPluginConfigData, SiteMapPluginConfigData> = {
   // Merge together all of the individual sitemaps from each source
-  async afterUpdate(_, { sharedFilesystem, globalConfig }) {
+  async afterUpdate(_, { sharedFilesystem, globalConfig }, { siteUrl }) {
```
Comment (DavieReid) [inline packages/plugins/src/SiteMapPlugin.ts:10]: Should there not be a `SiteMapPluginOptions` type somewhere with `siteUrl` specified?

File: packages/site/.env [hunk 2]
```diff
@@ -4,4 +4,5 @@
 # ... env.local - to override these env vars when running a LOCALHOST version
 # ... env.test  - to override these env vars when running a TEST version
 # ... env.prod  - to override these env vars when running a PROD version
-NEXT_PUBLIC_ENABLE_LOGIN=false
\ No newline at end of file
+NEXT_PUBLIC_ENABLE_LOGIN=false
+SITE_URL=https://mosaic-mosaic-dev-team.vercel.app/
```
Comment (DavieReid) [inline packages/site/.env:8]: Vercel has an env variable for the site URL https://vercel.com/docs/concepts/projects/environment-variables/system-environment-variables#framework-environment-variables

I guess this wouldnt work for us at the moment because we generate the snapshot locally then upload it to vercel

**Comment by DavieReid** [comment]
Needs a changset

**Comment by lilyvc** [comment]
> Needs a changset

added

File: packages/plugins/src/SiteMapPlugin.ts (hunk 1 above)
Comment (lilyvc) [reply packages/plugins/src/SiteMapPlugin.ts:19]: added

**Review by DavieReid — APPROVED** [review]
